version: '3'

services:
  api:
    build: .
    command: 'uvicorn src.run:app --host 0.0.0.0'
    volumes:
      - ./:/app/
    env_file:
      - .env
    ports:
      - 8003:8000
    depends_on:
      - db
  celery:
    build: .
    command: 'celery -A src.tasks worker'
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
  flower:
    build: .
    command: 'celery -A src.tasks flower'
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - 8004:5555
  redis:
    image: redis:7-alpine
    expose:
      - 6379
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    expose:
      - 5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=calc_db
volumes:
  postgres_data:
